// api/_quotepdf.js — reading a Touchstone quote PDF.
//
// Underscore: a helper, not a route. And separated from api/import-pdf.js for
// the same reason api/_jobs.js is separated from api/import-jobs.js — the
// interesting failures are all in the reading, and reading that lives inside a
// route can only be tested by standing up a database and signing a token.
//
// THIS DOES NOT ASK AN AI WHAT THE PDF SAYS.
//
//   api/import-quote.js sends a PDF to the Claude API and asks it to describe
//   the contents. That is the right tool when the input could be anything. It
//   is the WRONG tool here, and the difference is worth stating because the
//   easy thing would have been to reuse it:
//
//     - These are Touchstone's own quotes, generated by one template. The text
//       sits at fixed coordinates: the client block starts at x=29, the venue
//       block at x=428, a category's money at x>=450 with its name on the row
//       below at x=41. That is not a document to be interpreted; it is a form
//       to be read.
//     - An extraction that is read has a right answer. An extraction that is
//       inferred has a plausible one. These are dollar figures going into a
//       year's revenue, and "plausible" is the failure mode that does not
//       announce itself.
//     - It costs nothing, needs no API key, and answers in milliseconds, so
//       twenty-five PDFs is a progress bar rather than a bill.
//
//   And it can be PROVEN, which the other cannot: the categories have to add
//   up to the grand total printed on the same page. See `checkSum` below. That
//   one arithmetic check is worth more than any amount of care in a prompt.
//
// The input is deliberately NOT a pdfjs object. It is plain data —
// `pages: [[{ str, x, y }, ...], ...]` — so the whole of this file can be
// tested against a fixture, and so swapping the text extractor out later
// touches one file and not this one.

/* ---------------------------------------------------------------------------
   Rows.

   A PDF has no lines, only glyphs with coordinates. Two items are on the same
   row when their baselines are within a couple of points — the tolerance is
   not cosmetic: "San Francisco CA" and "94104" are separate items on one row,
   and a tolerance too tight turns an address into two addresses.
   --------------------------------------------------------------------------- */
export const ROW_TOL = 3;

export function toRows(items, tol = ROW_TOL) {
  const live = (items || []).filter((i) => i && String(i.str || "").trim());
  const rows = [];
  for (const it of live) {
    const y = Number(it.y);
    let row = rows.find((r) => Math.abs(r.y - y) <= tol);
    if (!row) { row = { y, items: [] }; rows.push(row); }
    row.items.push({ str: String(it.str), x: Number(it.x), y });
  }
  for (const r of rows) {
    r.items.sort((a, b) => a.x - b.x);
    /* The row's own y is re-set to the TOPMOST glyph on it. Rows are ordered by
       this, and a row seeded by a glyph that happens to sit a point lower than
       its neighbours would otherwise sort below a row it is above. */
    r.y = Math.max(...r.items.map((i) => i.y));
    r.text = r.items.map((i) => i.str.trim()).filter(Boolean).join(" ").replace(/\s+/g, " ");
  }
  rows.sort((a, b) => b.y - a.y);            // top of the page first
  return rows;
}

/* Every row of every page, in reading order, each tagged with its page. */
export function allRows(pages) {
  const out = [];
  (pages || []).forEach((items, p) => {
    toRows(items).forEach((r) => out.push({ ...r, page: p }));
  });
  return out;
}

const norm = (s) => String(s == null ? "" : s).replace(/\s+/g, " ").trim();
const MONEY = /^\$?-?[\d,]+\.\d{2}$/;

export function cents(v) {
  const s = String(v == null ? "" : v).replace(/[$,\s]/g, "");
  if (!/^-?\d+(\.\d+)?$/.test(s)) return null;
  return Math.round(parseFloat(s) * 100);
}
export const dollars = (c) => Math.round(c) / 100;

/* Items on a row inside a horizontal band, joined left to right. */
const inBand = (row, x0, x1) =>
  norm(row.items.filter((i) => i.x >= x0 && i.x < x1).map((i) => i.str).join(" "));

/* ---------------------------------------------------------------------------
   The blocks.
   --------------------------------------------------------------------------- */

/* "Bill To:" on the left, "Event Details:" on the right, each a name followed
   by however many address lines it has. The split is taken from where
   "Event Details:" actually starts rather than from a number typed in here, so
   a template that moves the column still reads.
 *
 * WHERE THE BLOCK ENDS, AND WHY IT IS A LANDMARK AND NOT A GAP
 *
 *   The first version had no end at all: it read until a row was empty in both
 *   columns, and on this template no such row exists before the bottom of the
 *   page. So the client's address came back as its street, then the job title,
 *   then the quote number, then the load-in times, then four projectors —
 *   which would have gone straight into the Clients directory as a new
 *   company's billing address.
 *
 *   The obvious fix is to stop at a vertical gap bigger than the line spacing.
 *   That works on this document and is a guess about typography: a client with
 *   a one-line address gives you no line spacing to measure, and the rule
 *   silently becomes something else.
 *
 *   So it stops at a LANDMARK the template actually has — the row carrying the
 *   job name, which is the next thing down the page. `stopIdx` is that row. If
 *   the caller cannot find it, this does not fall back to a guess; the parse
 *   fails and says so, because a document with no "Quote Number" on it is not
 *   one of these quotes and should not be read as though it were.
 */
function twoColumnBlock(rows, stopIdx) {
  const headIdx = rows.findIndex((r) => /^bill to:?$/i.test(norm(r.items[0] && r.items[0].str)));
  if (headIdx < 0) return null;
  const head = rows[headIdx];
  const right = head.items.find((i) => /^event details:?$/i.test(norm(i.str)));
  if (!right) return null;
  const split = right.x - 5;
  const end = Number.isInteger(stopIdx) && stopIdx > headIdx ? stopIdx : rows.length;

  const left = [], rightLines = [];
  for (let i = headIdx + 1; i < end; i++) {
    const r = rows[i];
    if (r.page !== head.page) break;
    const l = inBand(r, -1e6, split);
    const rr = inBand(r, split, 1e6);
    /* A gap in ONE column is ordinary — a two-line client address beside a
       three-line venue one — so an empty side is skipped, not a stop. */
    if (l) left.push(l);
    if (rr) rightLines.push(rr);
  }
  return { left, right: rightLines };
}

/* name + address out of a block of lines: the first line is the name, the rest
   are the address. */
function nameAndAddress(lines) {
  const ls = (lines || []).map(norm).filter(Boolean);
  if (!ls.length) return { name: "", address: "" };
  return { name: ls[0], address: ls.slice(1).join(", ") };
}

/* "757 Market St, San Francisco CA 94104" -> the pieces the venues table keeps.
   Deliberately forgiving: anything it cannot place stays in `address`, which
   is the field that is always shown, so nothing is ever lost by this. */
export function splitAddress(address) {
  const s = norm(address);
  if (!s) return { address: "", city: "", state: "", zip: "" };
  const parts = s.split(",").map(norm).filter(Boolean);
  const tail = parts.length > 1 ? parts[parts.length - 1] : s;
  const m = tail.match(/^(.*?)\s*\b([A-Z]{2})\b\s*(\d{5}(?:-\d{4})?)?$/);
  if (!m) return { address: s, city: "", state: "", zip: "" };
  const city = norm(m[1]);
  const state = m[2];
  const zip = m[3] || "";
  const street = parts.length > 1 ? parts.slice(0, -1).join(", ") : "";
  /* A tail with a state but no city ("CA 94104") is not a city line; put the
     whole thing back rather than inventing an empty city. */
  if (!city && !street) return { address: s, city: "", state, zip };
  return { address: street || s, city, state, zip };
}

/* ---------------------------------------------------------------------------
   The detail strip: Revision | Load In | Load Out | Event Timeframe | Venue.

   The labels define the columns. Values sit on the rows underneath at the same
   x, and a value can run to more than one row (the venue block does).
   --------------------------------------------------------------------------- */
function detailStrip(rows) {
  const headIdx = rows.findIndex((r) => r.items.some((i) => /^load in:?$/i.test(norm(i.str))));
  if (headIdx < 0) return {};
  const head = rows[headIdx];
  const cols = head.items
    .map((i) => ({ label: norm(i.str).replace(/:$/, ""), x: i.x }))
    .sort((a, b) => a.x - b.x);

  const out = {};
  for (let c = 0; c < cols.length; c++) {
    const x0 = cols[c].x - 5;
    const x1 = c + 1 < cols.length ? cols[c + 1].x - 5 : 1e6;
    const lines = [];
    for (let i = headIdx + 1; i < rows.length; i++) {
      const r = rows[i];
      if (r.page !== head.page) break;
      /* The strip ends where the items table begins. */
      if (r.items.some((it) => /^items$/i.test(norm(it.str)))) break;
      const v = inBand(r, x0, x1);
      if (v) lines.push(v);
      if (lines.length > 8) break;
    }
    out[cols[c].label.toLowerCase()] = lines.join(" ");
  }
  return out;
}

/* "04-27-2026 9:00 AM" -> { date: "04-27-2026", time: "9:00 AM" } */
export function splitDateTime(v) {
  const s = norm(v);
  const m = s.match(/^(\d{1,2}[-/.]\d{1,2}[-/.]\d{2,4})\s*(.*)$/);
  if (!m) return { date: "", time: "" };
  return { date: m[1], time: norm(m[2]).replace(/\s*to$/i, "") };
}

/* ---------------------------------------------------------------------------
   The money.

   A category is a row carrying one amount on the right, with its NAME ON THE
   ROW BELOW on the left — which reads backwards and is simply how the template
   lays it out. Everything on the left between that name and the next amount is
   the gear inside it.
   --------------------------------------------------------------------------- */
const LEFT_X = 120;           // the items column; category names and gear live here
const RIGHT_X = 380;          // the money column

function isMoneyRow(r) {
  const right = r.items.filter((i) => i.x >= RIGHT_X);
  if (right.length !== 1) return false;
  if (r.items.some((i) => i.x < LEFT_X)) return false;   // a row with a label is not a bare amount
  return MONEY.test(norm(right[0].str));
}

function grandTotalRow(rows) {
  return rows.find((r) => r.items.some((i) => /^grand total$/i.test(norm(i.str))) &&
                          r.items.some((i) => MONEY.test(norm(i.str))));
}

/* "2 x 12K Laser Projector" -> { qty: 2, name: "12K Laser Projector" }
   "Labor -A1"              -> { qty: 1, name: "Labor -A1" }
   Labour lines carry no count in this template, and inventing one would be a
   number nobody wrote down. */
export function splitQty(line) {
  const s = norm(line);
  const m = s.match(/^(\d+)\s*[x×]\s+(.+)$/i);
  if (!m) return { qty: 1, name: s, counted: false };
  return { qty: parseInt(m[1], 10), name: norm(m[2]), counted: true };
}

function categories(rows) {
  const gt = grandTotalRow(rows);
  /* Everything after the grand total is client responsibilities, signature
     blocks and eight pages of terms. Stopping here is what keeps a paragraph
     about rigging fees out of the gear list. */
  const end = gt ? rows.indexOf(gt) : rows.length;
  const body = rows.slice(0, end);

  const out = [];
  for (let i = 0; i < body.length; i++) {
    if (!isMoneyRow(body[i])) continue;
    const amount = cents(body[i].items.find((x) => x.x >= RIGHT_X).str);
    if (amount === null) continue;

    /* The name is the next row that has something in the left column. */
    let j = i + 1;
    while (j < body.length && !body[j].items.some((x) => x.x < LEFT_X)) j++;
    if (j >= body.length) continue;
    const name = inBand(body[j], -1e6, LEFT_X);
    if (!name) continue;

    const items = [];
    for (let k = j + 1; k < body.length; k++) {
      if (isMoneyRow(body[k])) break;
      const line = inBand(body[k], -1e6, LEFT_X);
      if (!line) continue;
      /* The "Items / Total" header repeats at the top of every page, and a
         category's gear list runs straight through a page break, so it lands
         in the middle of one. It is furniture, not a line item.
         Checked against the LEFT COLUMN's text rather than the whole row's:
         the row reads "Items    Total" because the price column has a heading
         too, so a test for a row that says exactly "items" never fires and is
         a guard that only looks like one. */
      if (/^items$/i.test(line)) continue;
      items.push(splitQty(line));
    }
    out.push({ name, amount, items });
    i = j;
  }
  return { categories: out, total: gt ? cents(gt.items.filter((x) => MONEY.test(norm(x.str))).pop().str) : null };
}

/* ---------------------------------------------------------------------------
   The whole thing.
   --------------------------------------------------------------------------- */
export function parseQuotePdf(pages) {
  const rows = allRows(pages);
  if (!rows.length) return { ok: false, error: "There is no text in that PDF. If it is a scan, it cannot be read." };

  const warnings = [];

  /* The job name and the quote number are found FIRST, because the name's row
     is what bounds the address block above it. */
  const qnIdx = rows.findIndex((r) => r.items.some((i) => /^quote number$/i.test(norm(i.str))));
  if (qnIdx < 0) {
    return {
      ok: false,
      error: "That does not look like a Touchstone quote — there is no " +
             "\"Quote Number\" on it. Add it with the paste importer instead.",
    };
  }
  const quoteNumber = norm(rows[qnIdx].items
    .filter((i) => !/^quote number$/i.test(norm(i.str)))
    .map((i) => i.str).join(" "));

  let name = "", nameIdx = -1;
  for (let i = qnIdx - 1; i >= 0; i--) {
    const t = norm(rows[i].text);
    if (!t) continue;
    if (/^bill to:?$/i.test(t)) break;
    name = t; nameIdx = i;
    break;
  }

  const block = twoColumnBlock(rows, nameIdx);
  const client = block ? nameAndAddress(block.left) : { name: "", address: "" };
  const venue = block ? nameAndAddress(block.right) : { name: "", address: "" };

  const strip = detailStrip(rows);
  const loadIn = splitDateTime(strip["load in"]);
  const loadOut = splitDateTime(strip["load out"]);
  const revision = norm(strip.revision);

  const { categories: cats, total } = categories(rows);

  if (!name) warnings.push("Couldn't find the job name.");
  if (!client.name) warnings.push("Couldn't find the client.");
  if (!venue.name) warnings.push("Couldn't find the venue.");
  if (!loadIn.date) warnings.push("Couldn't find the load-in date.");
  if (total === null) warnings.push("Couldn't find the grand total.");
  if (!cats.length) warnings.push("Couldn't find any category amounts.");

  /* THE CHECK THAT MAKES THIS TRUSTWORTHY.
     The categories are printed on the same page as the grand total and have to
     add up to it. If they do not, something was misread — and it is better to
     say so on the review screen than to import a job whose parts and whole
     disagree. This is the one assurance an AI extraction could never give. */
  const sum = cats.reduce((t, c) => t + c.amount, 0);
  const balances = total !== null && cats.length > 0 && sum === total;
  /* Reported through `check` and NOT also pushed onto `warnings`.
     It was in both at first, and the review screen dutifully printed it twice
     — once formatted with currency, once raw — which reads like two different
     problems with the same quote. One fact, one place. */

  return {
    ok: !!(name && total !== null && loadIn.date),
    client,
    venue: { ...venue, ...splitAddress(venue.address) },
    name,
    quoteNumber,
    revision,
    loadIn, loadOut,
    startDate: loadIn.date,
    endDate: loadOut.date || loadIn.date,
    total: total === null ? null : dollars(total),
    categories: cats.map((c) => ({
      name: c.name,
      amount: dollars(c.amount),
      items: c.items,
    })),
    check: {
      categoriesTotal: dollars(sum),
      balances,
    },
    warnings,
  };
}

/* ---------------------------------------------------------------------------
   Turning a parsed quote into quote lines.

   WHERE THE MONEY SITS, AND WHY IT SITS THERE
     The PDF prices CATEGORIES, not items. "General Session - Video, $7,880" and
     six pieces of gear underneath it with no prices on them at all.

     So the category carries the money and the gear is recorded at zero. The
     alternative — dividing the category across its items — would put a number
     against every projector that nobody at Touchstone ever wrote down, and it
     would look exactly as authoritative as a real one.

     What this buys: the item report can honestly count how many times a 12K
     projector went out and on how many shows, which is what the counting is
     for, while revenue stays on the rows that actually carry a price.
   --------------------------------------------------------------------------- */
const DEPT_HINTS = [
  [/\bvideo\b|\bprojection\b|\bled\b|\bcamera\b|\bbroadcast\b/i, "Video"],
  [/\baudio\b|\bsound\b|\bmic\b/i, "Audio"],
  [/\blight/i, "Lighting"],
  [/\bpower\b|\bdistro\b|\bgenerator\b/i, "Power"],
  [/\bscenic\b|\bdrape\b|\bstag|\btruss\b|\brig/i, "Scenic"],
  [/\blabor\b|\bcrew\b|\bstagehand\b/i, "Labor"],
];
export function deptOf(name) {
  const s = String(name || "");
  for (const [re, d] of DEPT_HINTS) if (re.test(s)) return d;
  return "Misc";
}

export function linesFor(parsed) {
  const lines = [];
  let n = 0;
  for (const c of parsed.categories || []) {
    const dept = deptOf(c.name);
    lines.push({
      id: "cat" + (++n),
      kind: "category",
      name: c.name,
      department: dept,
      qty: 1, days: 1, rate: c.amount, discount: 0,
    });
    for (const it of c.items || []) {
      lines.push({
        id: "itm" + (++n),
        kind: "item",
        name: it.name,
        department: deptOf(it.name) === "Misc" ? dept : deptOf(it.name),
        qty: it.qty, days: 1,
        /* Zero, and meant. See the note above. */
        rate: 0, discount: 0,
      });
    }
  }
  return lines;
}
